In [1]:
import cv2
import numpy as np

In [2]:
# by default parameter for reading image color if you dont specify automatically it will use that 
img = cv2.imread('watch.jpg',cv2.IMREAD_COLOR)  

In [3]:
# choosing specific pixels
px = img[55,55]

In [4]:
# changing the pixel
img[55,55] = [255,255,255]

In [5]:
# re-reference 
px = img[100:150, 100:150]
print(px)

[[[ 53  48  57]
  [ 53  48  57]
  [ 54  46  56]
  ...
  [ 36  36  42]
  [ 36  36  42]
  [ 56  56  62]]

 [[ 48  43  52]
  [ 50  45  54]
  [ 53  45  55]
  ...
  [ 36  34  40]
  [ 42  40  46]
  [ 39  37  43]]

 [[ 46  41  50]
  [ 47  42  51]
  [ 51  43  53]
  ...
  [ 33  33  39]
  [ 33  33  39]
  [ 56  56  62]]

 ...

 [[ 25  34  47]
  [ 27  36  49]
  [ 30  39  53]
  ...
  [105 114 128]
  [106 114 131]
  [106 114 131]]

 [[ 27  36  50]
  [ 26  35  49]
  [ 26  35  49]
  ...
  [ 96 110 129]
  [105 116 138]
  [109 120 142]]

 [[ 27  36  50]
  [ 25  34  48]
  [ 25  34  48]
  ...
  [101 114 136]
  [100 112 136]
  [107 117 141]]]


In [12]:
img[100:150,100:150] = [255,255,255]

In [13]:
print(img.shape)
print(img.size)
print(img.dtype)

(168, 300, 3)
151200
uint8


In [14]:
watch_face = img[37:111,107:194]
img[0:74,0:87] = watch_face

cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()