In [1]:
import numpy as np
import cv2

In [2]:
img = cv2.imread('watch.jpg',cv2.IMREAD_COLOR)

In [3]:
# drawing line on image
# first paramter = image on which line to be drawn
# second paramter = x1,y1 co-ordinate
# third paramter = x2,y2 co-ordinate  // basically they are pixels
# fourth parameter = color of line in RGB
cv2.line(img,(0,0),(150,150),(255,255,255))

array([[[255, 255, 255],
        [ 31,  27,  33],
        [ 31,  27,  33],
        ...,
        [ 37,  33,  45],
        [ 38,  34,  46],
        [ 40,  36,  48]],

       [[ 32,  28,  34],
        [255, 255, 255],
        [ 30,  26,  32],
        ...,
        [ 34,  30,  42],
        [ 35,  31,  43],
        [ 35,  31,  43]],

       [[ 32,  30,  36],
        [ 30,  28,  34],
        [255, 255, 255],
        ...,
        [ 31,  27,  38],
        [ 32,  28,  40],
        [ 31,  27,  39]],

       ...,

       [[ 46,  54,  71],
        [ 42,  50,  67],
        [ 40,  48,  65],
        ...,
        [ 40,  62,  97],
        [ 37,  60,  92],
        [ 41,  64,  96]],

       [[ 35,  45,  62],
        [ 44,  54,  71],
        [ 48,  58,  75],
        ...,
        [ 39,  64,  98],
        [ 40,  65,  97],
        [ 37,  62,  94]],

       [[ 39,  49,  66],
        [ 34,  44,  61],
        [ 35,  45,  62],
        ...,
        [ 46,  71, 105],
        [ 47,  72, 106],
        [ 46,  71, 103]]

In [4]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
# to give thickness pass fifth parameter
cv2.line(img,(0,0),(150,150),(255,255,255),15)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 37,  33,  45],
        [ 38,  34,  46],
        [ 40,  36,  48]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 34,  30,  42],
        [ 35,  31,  43],
        [ 35,  31,  43]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 31,  27,  38],
        [ 32,  28,  40],
        [ 31,  27,  39]],

       ...,

       [[ 46,  54,  71],
        [ 42,  50,  67],
        [ 40,  48,  65],
        ...,
        [ 40,  62,  97],
        [ 37,  60,  92],
        [ 41,  64,  96]],

       [[ 35,  45,  62],
        [ 44,  54,  71],
        [ 48,  58,  75],
        ...,
        [ 39,  64,  98],
        [ 40,  65,  97],
        [ 37,  62,  94]],

       [[ 39,  49,  66],
        [ 34,  44,  61],
        [ 35,  45,  62],
        ...,
        [ 46,  71, 105],
        [ 47,  72, 106],
        [ 46,  71, 103]]

In [6]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [7]:
# drawing rectangle 
cv2.rectangle(img,(15,25),(200,150),(0,0,255),15)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 37,  33,  45],
        [ 38,  34,  46],
        [ 40,  36,  48]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 34,  30,  42],
        [ 35,  31,  43],
        [ 35,  31,  43]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 31,  27,  38],
        [ 32,  28,  40],
        [ 31,  27,  39]],

       ...,

       [[ 46,  54,  71],
        [ 42,  50,  67],
        [ 40,  48,  65],
        ...,
        [ 40,  62,  97],
        [ 37,  60,  92],
        [ 41,  64,  96]],

       [[ 35,  45,  62],
        [ 44,  54,  71],
        [ 48,  58,  75],
        ...,
        [ 39,  64,  98],
        [ 40,  65,  97],
        [ 37,  62,  94]],

       [[ 39,  49,  66],
        [ 34,  44,  61],
        [ 35,  45,  62],
        ...,
        [ 46,  71, 105],
        [ 47,  72, 106],
        [ 46,  71, 103]]

In [8]:
# drawing cirlce
# parameters are the image, the center of the circle, the radius, color, and thickness
cv2.circle(img,(100,63), 55, (0,255,0), -1)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 37,  33,  45],
        [ 38,  34,  46],
        [ 40,  36,  48]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 34,  30,  42],
        [ 35,  31,  43],
        [ 35,  31,  43]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 31,  27,  38],
        [ 32,  28,  40],
        [ 31,  27,  39]],

       ...,

       [[ 46,  54,  71],
        [ 42,  50,  67],
        [ 40,  48,  65],
        ...,
        [ 40,  62,  97],
        [ 37,  60,  92],
        [ 41,  64,  96]],

       [[ 35,  45,  62],
        [ 44,  54,  71],
        [ 48,  58,  75],
        ...,
        [ 39,  64,  98],
        [ 40,  65,  97],
        [ 37,  62,  94]],

       [[ 39,  49,  66],
        [ 34,  44,  61],
        [ 35,  45,  62],
        ...,
        [ 46,  71, 105],
        [ 47,  72, 106],
        [ 46,  71, 103]]

In [9]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
# to write some text on image
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(img,'OpenCV Tuts!',(0,130), font, 1, (200,255,155), 2, cv2.LINE_AA)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 37,  33,  45],
        [ 38,  34,  46],
        [ 40,  36,  48]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 34,  30,  42],
        [ 35,  31,  43],
        [ 35,  31,  43]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 31,  27,  38],
        [ 32,  28,  40],
        [ 31,  27,  39]],

       ...,

       [[ 46,  54,  71],
        [ 42,  50,  67],
        [ 40,  48,  65],
        ...,
        [ 40,  62,  97],
        [ 37,  60,  92],
        [ 41,  64,  96]],

       [[ 35,  45,  62],
        [ 44,  54,  71],
        [ 48,  58,  75],
        ...,
        [ 39,  64,  98],
        [ 40,  65,  97],
        [ 37,  62,  94]],

       [[ 39,  49,  66],
        [ 34,  44,  61],
        [ 35,  45,  62],
        ...,
        [ 46,  71, 105],
        [ 47,  72, 106],
        [ 46,  71, 103]]

In [11]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# drawing pentagons
pts = np.array([[10,5],[20,30],[70,20],[50,10]], np.int32)
# OpenCV documentation had this code, which reshapes the array to a 1 x 2. I did not 
# find this necessary, but you may:
# pts = pts.reshape((-1,1,2))
# The parameters are as follows: where is the object being drawn to, 
# the coordinates, should we "connect" the final and starting dot, 
# the color, and thickness.
cv2.polylines(img, [pts], True, (0,255,255), 3)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 37,  33,  45],
        [ 38,  34,  46],
        [ 40,  36,  48]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 34,  30,  42],
        [ 35,  31,  43],
        [ 35,  31,  43]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [ 31,  27,  38],
        [ 32,  28,  40],
        [ 31,  27,  39]],

       ...,

       [[ 46,  54,  71],
        [ 42,  50,  67],
        [ 40,  48,  65],
        ...,
        [ 40,  62,  97],
        [ 37,  60,  92],
        [ 41,  64,  96]],

       [[ 35,  45,  62],
        [ 44,  54,  71],
        [ 48,  58,  75],
        ...,
        [ 39,  64,  98],
        [ 40,  65,  97],
        [ 37,  62,  94]],

       [[ 39,  49,  66],
        [ 34,  44,  61],
        [ 35,  45,  62],
        ...,
        [ 46,  71, 105],
        [ 47,  72, 106],
        [ 46,  71, 103]]

In [13]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()